/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/andy/Documents/Projects/Retrocomp/ZX-Spectrum/karabas-pro/firmware/src/fpga/profi/syn/al3a10/al_ip/altpll0.v
 ** Date	:	2023 01 13
 ** TD version	:	4.6.18154
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             50.000Mhz
//	Clock multiplication factor: 9
//	Clock division factor:       4
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 112.500000MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module altpll0(refclk,
		reset,
		extlock,
		clk0_out);

	input refclk;
	input reset;
	output extlock;
	output clk0_out;

	wire clk0_buf;

	AL_LOGIC_BUFG bufg_feedback( .i(clk0_buf), .o(clk0_out) );

	AL_PHY_PLL #(.DPHASE_SOURCE("DISABLE"),
		.FIN("50.000"),
		.FEEDBK_MODE("NORMAL"),
		.FEEDBK_PATH("CLKC0_EXT"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("DISABLE"),
		.DERIVE_PLL_CLOCKS("DISABLE"),
		.GEN_BASIC_CLOCK("DISABLE"),
		.GMC_GAIN("0"),
		.ICP_CURRENT(9),
		.KVCO("2"),
		.LPF_CAPACITOR("2"),
		.LPF_RESISTOR(8),
		.REFCLK_DIV(4),
		.FBCLK_DIV(9),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(9),
		.CLKC0_CPHASE(8),
		.CLKC0_FPHASE("0")	)
	pll_inst (.refclk(refclk),
		.pllreset(reset),
		.stdby(1'b0),
		.ext_lock(extlock),
		.scanclk(1'b0),
		.phaseupdown(1'b0),
		.phasestep(1'b0),
		.phcntsel(3'b000),
		.phasedone(open),
		.fbclk(clk0_out),
		.clkc({open, open, open, open, clk0_buf}));

endmodule
