/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/andy/Documents/Projects/Retrocomp/ZX-Spectrum/karabas-pro/firmware/src/fpga/profi/syn/al3a10/al_ip/altpll1.v
 ** Date	:	2023 01 13
 ** TD version	:	4.6.18154
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             112.000Mhz
//	Clock multiplication factor: 3
//	Clock division factor:       4
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 84.000000 MHZ	| 0  DEG     
//		C1        	| 72.000000 MHZ	| 0  DEG     
//		C2        	| 28.000000 MHZ	| 0  DEG     
//		C3        	| 24.000000 MHZ	| 0  DEG     
//		C4        	| 8.000000  MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module altpll1(refclk,
		reset,
		extlock,
		clk0_out,
		clk1_out,
		clk2_out,
		clk3_out,
		clk4_out);

	input refclk;
	input reset;
	output extlock;
	output clk0_out;
	output clk1_out;
	output clk2_out;
	output clk3_out;
	output clk4_out;

	wire clk0_buf;

	AL_LOGIC_BUFG bufg_feedback( .i(clk0_buf), .o(clk0_out) );

	AL_PHY_PLL #(.DPHASE_SOURCE("DISABLE"),
		.FIN("112.000"),
		.FEEDBK_MODE("NORMAL"),
		.FEEDBK_PATH("CLKC0_EXT"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("DISABLE"),
		.DERIVE_PLL_CLOCKS("DISABLE"),
		.GEN_BASIC_CLOCK("DISABLE"),
		.GMC_GAIN("2"),
		.ICP_CURRENT(9),
		.KVCO("2"),
		.LPF_CAPACITOR("1"),
		.LPF_RESISTOR(8),
		.REFCLK_DIV(4),
		.FBCLK_DIV(3),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(12),
		.CLKC0_CPHASE(11),
		.CLKC0_FPHASE("0"),
		.CLKC1_ENABLE("ENABLE"),
		.CLKC1_DIV(14),
		.CLKC1_CPHASE(13),
		.CLKC1_FPHASE("0"),
		.CLKC2_ENABLE("ENABLE"),
		.CLKC2_DIV(36),
		.CLKC2_CPHASE(35),
		.CLKC2_FPHASE("0"),
		.CLKC3_ENABLE("ENABLE"),
		.CLKC3_DIV(42),
		.CLKC3_CPHASE(41),
		.CLKC3_FPHASE("0"),
		.CLKC4_ENABLE("ENABLE"),
		.CLKC4_DIV(126),
		.CLKC4_CPHASE(125),
		.CLKC4_FPHASE("0")	)
	pll_inst (.refclk(refclk),
		.pllreset(reset),
		.stdby(1'b0),
		.ext_lock(extlock),
		.scanclk(1'b0),
		.phaseupdown(1'b0),
		.phasestep(1'b0),
		.phcntsel(3'b000),
		.phasedone(open),
		.fbclk(clk0_out),
		.clkc({clk4_out, clk3_out, clk2_out, clk1_out, clk0_buf}));

endmodule
