--------------------------------------------------------------
 --  Copyright (c) 2011-2021 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	/home/andy/Documents/Projects/Retrocomp/ZX-Spectrum/karabas-pro/firmware/src/fpga/profi/syn/al3a10/al_ip/altpll0.vhd
 -- Date	:	2023 01 13
 -- TD version	:	4.6.18154
--------------------------------------------------------------

-------------------------------------------------------------------------------
--	Input frequency:             50.000Mhz
--	Clock multiplication factor: 9
--	Clock division factor:       4
--	Clock information:
--		Clock name	| Frequency 	| Phase shift
--		C0        	| 112.500000MHZ	| 0  DEG     
-------------------------------------------------------------------------------

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
USE ieee.std_logic_unsigned.ALL;
USE ieee.std_logic_arith.ALL;
LIBRARY al3_macro;
USE al3_macro.AL_COMPONENTS.ALL;

ENTITY altpll0 IS
	PORT ( refclk	: IN	STD_LOGIC;
		reset	: IN	STD_LOGIC;
		extlock	: OUT	STD_LOGIC;
		clk0_out	: OUT	STD_LOGIC);
END altpll0;

ARCHITECTURE rtl OF altpll0 IS
	SIGNAL clk0_buf	: STD_LOGIC;
	SIGNAL fbk_wire	: STD_LOGIC;
	SIGNAL clkc_wire	: STD_LOGIC_VECTOR (4 DOWNTO 0);
BEGIN
	bufg_feedback : AL_LOGIC_BUFG
		PORT MAP ( i => clk0_buf, o => fbk_wire );

	pll_inst : AL_PHY_PLL	GENERIC MAP ( DPHASE_SOURCE => "DISABLE",
		FIN => "50.000",
		FEEDBK_MODE => "NORMAL",
		FEEDBK_PATH => "CLKC0_EXT",
		STDBY_ENABLE => "DISABLE",
		PLLRST_ENA => "ENABLE",
		SYNC_ENABLE => "DISABLE",
		DERIVE_PLL_CLOCKS => "DISABLE",
		GEN_BASIC_CLOCK => "DISABLE",
		GMC_GAIN => "0",
		ICP_CURRENT => 9,
		KVCO => "2",
		LPF_CAPACITOR => "2",
		LPF_RESISTOR => 8,
		REFCLK_DIV => 4,
		FBCLK_DIV => 9,
		CLKC0_ENABLE => "ENABLE",
		CLKC0_DIV => 9,
		CLKC0_CPHASE => 8,
		CLKC0_FPHASE => "0")
		PORT MAP ( refclk => refclk,
			pllreset => reset,
			stdby => '0',
			ext_lock => extlock,
			scanclk => '0',
			phaseupdown => '0',
			phasestep => '0',
			phcntsel => "000",
			fbclk => fbk_wire,
			clkc => clkc_wire);

		clk0_buf <= clkc_wire(0);
		clk0_out <= fbk_wire;

END rtl;
