--------------------------------------------------------------
 --  Copyright (c) 2011-2021 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	/home/andy/Documents/Projects/Retrocomp/ZX-Spectrum/karabas-pro/firmware/src/fpga/profi/syn/al3a10/al_ip/message_rom.vhd
 -- Date	:	2023 01 12
 -- TD version	:	4.6.18154
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY al3_macro;
	USE al3_macro.AL_COMPONENTS.all;

ENTITY message_rom IS
PORT (
	doa		: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);

	addra	: IN STD_LOGIC_VECTOR(2 DOWNTO 0);
	clka		: IN STD_LOGIC;
	rsta		: IN STD_LOGIC
	);
END message_rom;

ARCHITECTURE struct OF message_rom IS

	BEGIN
	inst : AL_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 8,
			ADDR_WIDTH_A	=> 3,
			DATA_DEPTH_A	=> 8,
			DATA_WIDTH_B	=> 8,
			ADDR_WIDTH_B	=> 3,
			DATA_DEPTH_B	=> 8,
			MODE			=> "SP",
			REGMODE_A	=> "NOREG",
			RESETMODE	=> "SYNC",
			IMPLEMENT	=> "9K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "../../../rtl/video/messages.mif",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia		=> (others=>'0'),
			dib		=> (others=>'0'),
			addra	=> addra,
			addrb	=> (others=>'0'),
			cea		=> '1',
			ceb		=> '0',
			clka		=> clka,
			clkb		=> '0',
			web		=> '0',
			rsta		=> rsta,
			rstb		=> '0',
			doa		=> doa,
			dob		=> OPEN,
			ocea		=> '0',
			oceb		=> '0'
		);

END struct;
