/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/andy/Documents/Projects/Retrocomp/ZX-Spectrum/karabas-pro/firmware/src/fpga/profi/syn/al3a10/al_ip/queue.v
 ** Date	:	2023 01 12
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module queue (
	rst,
	di, clkr, re, clkw, we,
	do,
	empty_flag,full_flag,rdusedw,wrusedw
 
);

	input rst;
	input [23:0] di;
	input clkw, we;
	input clkr,re;

	output [23:0] do;
	output empty_flag;
	output full_flag;
	output [8:0] rdusedw;
	output [8:0] wrusedw;

AL_LOGIC_RAMFIFO #(
 	.DATA_WIDTH(24),
	.ADDR_WIDTH(8),
	.SHOWAHEAD(0),
	.IMPLEMENT("AUTO")
)
logic_ramfifo(
	.rst(rst),
	.di(di),
	.clkw(clkw),
	.we(we),
	.do(do),
	.clkr(clkr),
	.re(re),
	.empty_flag(empty_flag),
	.full_flag(full_flag),
	.rdusedw(rdusedw),
	.wrusedw(wrusedw)
);

endmodule