/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/andy/Documents/Projects/Retrocomp/ZX-Spectrum/karabas-pro/firmware/src/fpga/profi/syn/al3a10/al_ip/rom_font1.v
 ** Date	:	2023 01 13
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module rom_font1 ( doa, addra, clka, rsta );

	output [7:0] doa;

	input  [10:0] addra;
	input  clka;
	input  rsta;




	AL_LOGIC_BRAM #( .DATA_WIDTH_A(8),
				.ADDR_WIDTH_A(11),
				.DATA_DEPTH_A(2048),
				.DATA_WIDTH_B(8),
				.ADDR_WIDTH_B(11),
				.DATA_DEPTH_B(2048),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../../../rtl/video/font.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({8{1'b0}}),
				.dib({8{1'b0}}),
				.addra(addra),
				.addrb({11{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule