--------------------------------------------------------------
 --  Copyright (c) 2011-2021 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	/home/andy/Documents/Projects/Retrocomp/ZX-Spectrum/karabas-pro/firmware/src/fpga/profi/syn/al3a10/al_ip/rtc.vhd
 -- Date	:	2023 01 12
 -- TD version	:	4.6.18154
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY al3_macro;
	USE al3_macro.AL_COMPONENTS.all;

ENTITY rtc IS
PORT (
	doa	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	wea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	dob	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
	dib	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	addrb	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	web	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC
	);
END rtc;

ARCHITECTURE struct OF rtc IS

	BEGIN

	inst : AL_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 8,
			DATA_WIDTH_B	=> 8,
			ADDR_WIDTH_A	=> 8,
			ADDR_WIDTH_b	=> 8,
			DATA_DEPTH_A	=> 256,
			DATA_DEPTH_B	=> 256,
			MODE		=> "DP",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "NOREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			RESETMODE	=> "SYNC",
			IMPLEMENT		=> "9K",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> dib,
			addra	=> addra,
			addrb	=> addrb,
			cea	=> '1',
			ceb	=> '1',
			ocea	=> '0',
			oceb	=> '0',
			clka	=> clka,
			clkb	=> clkb,
			wea	=> wea,
			web	=> web,
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			rsta	=> '0',
			rstb	=> '0',
			doa	=> doa,
			dob	=> dob
		);

END struct;
