/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/andy/Documents/Projects/Retrocomp/ZX-Spectrum/karabas-pro/firmware/src/fpga/profi/syn/al3a10/al_ip/screen1.v
 ** Date	:	2023 01 13
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module screen1 ( 
	doa, dia, addra, clka, wea,
	dob, dib, addrb, clkb, web
);

	output [15:0] doa;
	output [15:0] dob;


	input  [15:0] dia;
	input  [15:0] dib;
	input  [9:0] addra;
	input  [9:0] addrb;
	input  wea;
	input  web;
	input  clka;
	input  clkb;




	AL_LOGIC_BRAM #( .DATA_WIDTH_A(16),
				.DATA_WIDTH_B(16),
				.ADDR_WIDTH_A(10),
				.ADDR_WIDTH_B(10),
				.DATA_DEPTH_A(1024),
				.DATA_DEPTH_B(1024),
				.MODE("DP"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.WRITEMODE_B("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib(dib),
				.addra(addra),
				.addrb(addrb),
				.cea(1'b1),
				.ceb(1'b1),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(wea),
				.web(web),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(doa),
				.dob(dob));


endmodule